### PR TITLE
Update stuff, release with Github Actions

### PR DESCRIPTION
**Pull request by juulSme**
Hi @Thomas-Jean,

I've updated some stuff on top of @kristoff3r 's PR #3. Mainly bumped to Rust's blake3 1.3.3 and added a Github Actions release.yml workflow, which is usable if you add a `HEX_API_KEY` secret to your repo. I hope you have time to review and accept the PR!

Kind regards,

Julien

### CODE REVIEW

**Comment by kristoff3r** [comment]
This looks excellent. I haven't gotten a response in more than a year on my original PR, so if we want a proper release we might need to find an email to contact him, or simply fork it.

**Comment by juulSme** [comment]
I noticed :) I was thinking of giving it a month and otherwise I have this standing by: https://github.com/juulSme/blake3/compare/master...give-up-merge

**Comment by Thomas-Jean** [comment]
@juulSme Thank you for the CI action and updates
@kristoff3r  Thank you for the updates and the update to the rust code

I apologize for not seeing this, #2 sent me an automated email but #3 and #4  did not. I only saw this because it was on my GitHub dashboard under a few other reviews. I will see if I can get that fixed. Also, please let me know if either of you would like to be added as a contributor. I wrote this as a fun thing one weekend, so if either of you actively uses it for your work or your hobbies you may be better stewards of it.

edit:

I also bumped to 1.0.0 since the function name change it technically a breaking change.

**Comment by kristoff3r** [comment]
> @juulSme Thank you for the CI action and updates @kristoff3r Thank you for the updates and the update to the rust code
> 
> I apologize for not seeing this, #2 sent me an automated email but #3 and #4 did not. I only saw this because it was on my GitHub dashboard under a few other reviews. I will see if I can get that fixed. Also, please let me know if either of you would like to be added as a contributor. I wrote this as a fun thing one weekend, so if either of you actively uses it for your work or your hobbies you may be better stewards of it.

No worries, GitHub notifications are terrible, I only ever see stuff happening if I get emails.

We do use it in my company, but I'm more of a Rust person than an Elixir one, so I'd rather not be the main maintainer. I can help review/fix stuff if anything comes up though.

> edit:
> 
> I also bumped to 1.0.0 since the function name change it technically a breaking change.

That seems like the right move as everything seems pretty stable, but technically SemVer doesn't apply to versions below 1.0, see https://semver.org/#spec-item-4.

**Comment by juulSme** [comment]
> I apologize for not seeing this, #2 sent me an automated email but #3 and #4 did not. I only saw this because it was on my GitHub dashboard under a few other reviews. I will see if I can get that fixed. Also, please let me know if either of you would like to be added as a contributor. I wrote this as a fun thing one weekend, so if either of you actively uses it for your work or your hobbies you may be better stewards of it.

No problem, I have the same issue with the notifications :) I'm an Elixir dev primarily, you can add me as a contributor!

**Comment by Thomas-Jean** [comment]
@juulSme @kristoff3r I have sent you both invites. I plan to keep doing maintenance for this repo, but if I miss it again, you can all move stuff forward. Thank you!

**Pull request merged**
